services:
  db:
    image: postgres:18
    container_name: dragonball-db
    environment:
      POSTGRES_DB: dragonball
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  app:
    build: .
    container_name: dragonball-app
    depends_on:
      - db
    environment:
      DB_USER: postgres
      DB_PASSWORD: ${DB_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/dragonball
    ports:
      - "9090:9090"

volumes:
  postgres_data: